export const metadata = {
  title: 'Terms of Service — HipTrip',
};

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: `By accessing or using HipTrip ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. We may update these terms from time to time; continued use of the Service after changes are posted constitutes your acceptance of the revised terms.`,
  },
  {
    title: '2. Description of Service',
    body: `HipTrip is an AI-powered road trip planning platform that helps travelers discover routes, stops, and experiences along their journeys. Features include AI-generated trip itineraries, stop recommendations, saved trip management, and affiliate hotel suggestions. Some features require account registration.`,
  },
  {
    title: '3. User Accounts',
    body: `You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate, current, and complete information during registration and keep your account information updated. You agree to notify us immediately at support@hiptrip.net if you suspect unauthorized use of your account.`,
  },
  {
    title: '4. Acceptable Use',
    body: `You agree to use HipTrip only for lawful purposes and in accordance with these Terms. You may not: (a) use the Service in any way that violates applicable laws or regulations; (b) attempt to gain unauthorized access to any part of the Service or its related systems; (c) scrape, crawl, or extract data from the Service in bulk without written permission; (d) use the Service to transmit spam, malware, or other harmful content; or (e) impersonate any person or entity or misrepresent your affiliation with any person or entity.`,
  },
  {
    title: '5. AI-Generated Content',
    body: `Trip plans, stop suggestions, and itinerary content are generated by artificial intelligence and are provided for informational and entertainment purposes only. HipTrip does not guarantee the accuracy, completeness, or fitness for any particular purpose of AI-generated content. Route suggestions may not reflect current road conditions, closures, or safety hazards. Always verify directions and travel conditions before and during your trip. HipTrip is not liable for decisions made based on AI-generated content.`,
  },
  {
    title: '6. Affiliate Links and Third-Party Services',
    body: `HipTrip may display hotel recommendations and other travel services through affiliate partner links (including Expedia and Booking.com). When you click these links and make a booking, HipTrip may earn a commission. These affiliate relationships do not affect the price you pay. All transactions made through third-party services are governed by those parties' terms and privacy policies. HipTrip is not responsible for the products, services, or content of third-party sites.`,
  },
  {
    title: '7. Intellectual Property',
    body: `All content on HipTrip — including text, graphics, logos, software, and trip planning algorithms — is the property of HipTrip or its licensors and is protected by applicable intellectual property laws. You retain ownership of any trip content you create and save. By using the Service, you grant HipTrip a limited, non-exclusive license to store and display your saved trips and preferences to operate the Service.`,
  },
  {
    title: '8. Disclaimer of Warranties',
    body: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.`,
  },
  {
    title: '9. Limitation of Liability',
    body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HIPTRIP AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU EXCEED THE AMOUNT YOU PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM.`,
  },
  {
    title: '10. Governing Law',
    body: `These Terms are governed by the laws of the State of Delaware, United States, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved in the federal or state courts located in Delaware, and you consent to personal jurisdiction in those courts.`,
  },
  {
    title: '11. Contact Us',
    body: `If you have questions or concerns about these Terms of Service, please contact us at support@hiptrip.net. We aim to respond to all inquiries within 2 business days.`,
  },
];

import SimpleHeader from '../../components/SimpleHeader';

const TermsPage = () => (
  <>
    <SimpleHeader />
    <main className="min-h-screen bg-wayfarer-bg px-6 py-24 font-body text-wayfarer-text-main md:px-10">
      <div className="mx-auto w-full max-w-4xl space-y-8">
        <p className="text-xs font-semibold uppercase tracking-[0.18em] text-wayfarer-text-muted">
          Legal
        </p>
        <h1 className="font-display text-4xl font-bold text-wayfarer-primary md:text-5xl">
          Terms of Service
        </h1>
        <p className="max-w-3xl text-sm leading-relaxed text-wayfarer-text-muted">
          Last updated: April 5, 2026. Please read these terms carefully before using
          HipTrip.
        </p>

        <section className="space-y-4">
          {SECTIONS.map((section) => (
            <article
              key={section.title}
              className="rounded-2xl bg-wayfarer-surface p-6 shadow-wayfarer-soft"
            >
              <h2 className="mb-3 font-display text-lg font-semibold text-wayfarer-primary">
                {section.title}
              </h2>
              <p className="text-sm leading-relaxed text-wayfarer-text-muted">
                {section.body}
              </p>
            </article>
          ))}
        </section>
      </div>
    </main>
  </>
);

export default TermsPage;
